# Main font
font_family JetBrainsMono Nerd Font


# Emoji fallback
symbol_map U+1F300-U+1FAFF JoyPixels
symbol_map U+2600-U+26FF JoyPixels

# Panes: Ctrl+Shift+Enter splits to the right (vertical divider)
enabled_layouts splits
map kitty_mod+enter launch --location=vsplit --cwd=current

