max-gamma = 150

# Day
profile {
    time = 07:00
    identity = true
}

# Evening
profile {
    time = 19:00
    temperature = 5000
}

# Night
profile {
    time = 21:00
    temperature = 3500
    gamma = 0.9
}

# Late night
profile {
    time = 23:00
    temperature = 2800
    gamma = 0.8
}
